- .circleci/config.yml
- .pre-commit-config.yaml
- README.md
- app.py
- minio-start.sh
- requirements.in
- requirements.txt
- requirements_test.in
- requirements_test.txt
- test.py
Exposing via GET rather than a POST body which S3 does is deliberate.
- We expect that queries won't ever be too long: it is beyond the scope of the project to expose anything other than a basic filtering API, and maybe some very basic aggregate functions at most. Being limited by the length of URLs I think is fine.
- We could have URL-based caching, potentially using CloudFront down the line if we wanted to.
- Sharing/debugging should be fairly straightforward. You can paste a URL in a browser and see the filtered data. Literally any HTTP client should work: no need for any special library [other than a JSON decoder]
Not using boto3 deliberately. This does mean we have low-level code, but...
- To actually output JSON, we do have to do a little bit of faffing with bytes anyway, since S3 …
> S3 Select via GET happy path

- app.py
- app_aws.py
- test.py
This includes moving out some of the AWS-code into a separate module, to hopefully make the higher-level behaviour of the API clearer (which is expected to get more complex as features are added).
> Proxy data URLs according to current design

- app_aws.py
Bytes could theoretically build up in memory if the incoming chunk size was bigger than the output size, since the output chunk size was fixed and at most one chunk was output per input chunk.
This change also has a small (suspected) performance gain since there would be strictly less copying. Some bytes would also wait for less time in the generator, since those just beyond the output chunk size won't wait for an entire chunk.
> Robustness and more simplicity in chunk handling

- app.py
- test.py
This PR adds a new endpoint for pingdom healthcheck, in order for webops to monitor.
> adding healthcheck endpoint for pingdom

- app.py
- app_aws.py
- test.py
The slightly unfortunate thing is that the result does not have a header row. This is left to a future change
> feat: ability to query CSVs

- app.py
- templates/base.html
- templates/metadata.html
- test.py
Styling in GDS and refining is left to another PR. The current PR is still better than the raw JSON I think.
> feat: simple HTML page for metadata

- templates/metadata.html
Have invited DW to review, but treating this as trivial enough to not need it. So once tests pass, will merge + deploy
> feat: bulleted list of tables

- .coveragerc
Add source directory to coverage config to ensure all project files are picked
> fix: ensure root dir is included in coverage report

- requirements.txt
> ProxyFix incompatibility fix

- test_app.py
This becomes more important with graceful shutdown from processes coming up.
> tests: support more output from processes without blocking

- README.md
- templates/docs/index.html
Moving concepts and common parameters from Readme to docs
> moving concepts to docs

- app.py
- test_app.py
adding new list endpoints for datasets, versions and tables along with tests
> adding new list endpoints and tests

- app.py
- templates/docs/index.html
This PR introduces `base url`, reading from requst, so as to use within docs to make them complete
> introduce base url

- templates/docs/index.html
Further documentation refining, merging specific and latest sections of data API
> docs: merge specific version and latest bit of data API

- templates/docs/index.html
Documenting table data endpoint.
Fixing incorrect links.
> Docs add table api

- templates/docs/index.html
Change sql to multiline for readability
Rename `dataset-id` to `dataset` to match other variables
> change sql to multiline

- app_worker.py
This is to be able to use the same code to generate gzipped CSVs when the CSV is generated from a SQLite file, rather than JSON
> refactor: avoid json to csv conversion for gzipped csv

- README.md
- app.py
- templates/docs/index.html
> feat: document how to get support and report security vulnerabilities

- templates/docs/index.html
> docs: metadata endpoint

- templates/docs/index.html
> docs: clearer and more accurate examples using --data-urlencode

- app.py
- templates/metadata.html
- test_app.py
More complex datasets will include derived "reports": filtered and/or aggregated versions of the data. These are conceptually a bit different to "tables" which are more like the source data, and also won't be included in SQLite files (partially for size reasons)
---
Reviews can go commit by commit to see refactorings that allow the feature
> feat: support reports

- app.py
- app_aws.py
- test_app.py
The format does allow for the supply of metadata for all datasets, but for now, not doing that to allow for publishing a single dataset at a time to data.gov.uk. The addition of a new dataset is not frequent, and so is quite reasonable.
> feat: start of supplying data.json metadata for each dataset

- app_worker.py
- requirements.in
- requirements.txt
- requirements_test.txt
- test_app.py
Just like JSON is converted to CSVs, to then be individually downloaded or queries (with S3 Select) we now can convert SQLite to be converted to CSVs
> feat: extract SQLite to CSVs

- templates/docs/index.html
Some of the language is a bit clunky, but I think still better than not mentioning it.
> docs: mention SQLite

- templates/docs/index.html
The bullet points are all a bit more to do with the data, so I think it makes more sense.
> docs: put no auth right up front

- templates/docs/index.html
> docs: some information on simple queries

- templates/metadata.html
And avoid repeating the name / clunky language
> feat: put the fact that this is a dataset as a caption

- app.py
- test_app.py
Now it's got content, it should be fine to index
> feat: allow search indexing of front page

- .pre-commit-config.yaml
- requirements.txt
- requirements_test.txt
This is to present dates in YYYY-MM-DD format
> build(deps): bump stream-write-ods

- app_worker.py
The UncompressedSizeOverflowError means the zip can't fit into ZIP32, i.e.
LibreOffice wouldn't be able to open the file
> feat: ignore ODS file that would be too large for LibreOffice

- requirements_test.txt
- test_app.py
> build(deps): bump pytest to remove dependency on py

- app.py
https://platform.readme.trade.gov.uk/migrations/conducting-a-migration/02b-codebase-preparation/#logging:~:text=they%20become%20unhealthy.-,Web%20services,-All%20web%20applications
> healthcheck endpoint for dbt platform

- mock_sentry_app.py
- requirements.txt
- requirements_test.txt
In preparation to the move to DBT Platform, bumping packages to their latest versions.
> build(deps): bump sentry-sdk

- requirements.txt
- requirements_test.txt
This is done in preparation to the move to DBT Platform
> build(deps): bump sqlite-s3-query to latest

- README.md
There are technically a few more environment variables that affect documentation, but so far at DBT we don't use them in prod, so leaving to document them later.
> docs: document more environment variables

- .copilot/config.yml
- .copilot/image_build_run.sh
- .copilot/phases/build.sh
- .copilot/phases/install.sh
- .copilot/phases/post_build.sh
- .copilot/phases/pre_build.sh
- Set up the application codebase in preparation for migration from GOV.UK PaaS to DBT Platform
> chore: prepare application codebase for migration

- app_worker.py
The logging from the worker was logging on every http request, and because querying from SQLite files uses _many_ requests, the logs were too noisy to be helpful.
To address this, the httpx log level in the worker is increased from INFO to WARNING, and manual log messages have been put into key parts of the process.
> feat: better worker logging

- requirements_test.txt
Dependency updates to fix security issues
> chore: update deps to fix security vulnerabilities
