- .coveragerc
Some lines are being reported as not covered, when they must have been (e.g. a function declaration line, when the lines inside the function have been covered).
> Correct code coverage concurrency settings

- app_aws.py
The function `_read_multiple_chunks` will already raise NoMoreBytes if there aren't enough bytes, so no need to check if it returned anything
> Remove dead code / unnecessary check for no bytes

- app.py
- test.py
Requiring this to make it extremely explicit what the format will be: we will be supporting JSON and CSV.
Potentially down the line we could have a default, but we can add a default in a way that would likely be backward-compatible. We won't be able to remove it.
> Enforce format in the query string, and always return application/json as the content-type

- app.py
- test.py
This is for
- Clarity: it _is_ S3 Select
- Slightly more future friendliness for other query languages. Specifically, another SQL-based one
There is argument that we should abstract away the internal query language. At the moment, we're not doing that, so it's even slightly misleading to have the more abstract "query_sql". We can always add query_sql later in a backwards-compatible way.
Also using hyphens rather than underscores for consistency with path components
> More correct query parameter name

- app_aws.py
With large datasets, AWS doesn't like our current setting of 5_000_000
bytes for multipart uploads:
```xml
<Code>EntityTooSmall</Code>
<Message>Your proposed upload is smaller than the minimum allowed size</Message>
<ProposedSize>5000000</ProposedSize>
<MinSizeAllowed>5242880</MinSizeAllowed>
```
> fix: multipart upload chunk size

- app.py
- test.py
This PR adds `X-Robots-Tag` header to all responses, in order for search engines to ignore indexing.
> adding noindex header to responses

- README.md
- app.py
- mock_google_analytics_app.py
- test.py
- Send pageviews to google analytics without blocking the incoming request
- Disabled if no tracking tag is available in the environment
- Includes an update to tests to get them working on linux
- Hitting the mock sentry service more than 10 times causes the tests to hang
- Adds a new mock analytics app to allow for testing
Closes: https://trello.com/c/TyJFKLyq/1184-google-analytics-for-visibility-of-usage
> feat: track requests via google analytics.

- templates/metadata.html
It's 1-indexed and not 0-indexed
> fix: table index

- templates/metadata.html
'at' seems more for a time, rather than a date
> feat: change word for clarity

- templates/metadata.html
It's more for styling reasons: it's a bit borderline if this "should" be a table, but it is at least consistent with GOV.UK registers.
> feat: put column descriptions in a table

- app.py
- app_worker.py
- test.py
Some of the CSVs served by the public data api are quite large, this PR addresses this by returning a gzipped version of the CSV if the client passes an 'Accept-Encoding: gzip' header. The app_worker was changed to produce a gzipped version of each CSV alongside the original CSV.
https://trello.com/c/B57RhXkV/1333-faster-downloads-from-the-gateway-gzip-csv-files
> feature: serve gzip compressed csv's if client accepts gzip encoding

- app_aws.py
When offset gets set to 0, it should _not_ use the same chunk again. However, this is exactly what would happen if, say, the client requested 4 bytes and the existing chunk was exactly 4 bytes long.
> fix: edge case where could re-read the same data from the stream

- templates/docs/index.html
For clarity and to avoid mentioning S3 (since it's not really user-facing)
> feat: tweak about text

- app.py
- test_app.py
This is partially for tests so code coverage for the main process is written, which only happens on a terminate, not a kill
> feat: graceful shutdown

- templates/docs/index.html
Avoiding underscores is informed by https://www.gov.uk/guidance/gds-api-technical-and-data-standards where it states:
> use hyphens rather than underscores as word separators for multiword names
> docs: avoid abbreviations and underscores in ids

- templates/docs/index.html
(Going back a bit on my previous opinion) I don't think it needs to be quite as up front. After the more API-ish user-facing features I think is better.
> docs: move link to GitHub down slightly

- README.md
Now the API documentation is elsewhere, the README can specialise in information that's useful for development. So am putting the most relevant stuff for that up front. Specifically, how to run the tests is in prime position, and then how to run the application. It's deliberately in that order, since from tests is the preferred way to develop the API.
> docs: clearer README

- templates/docs/index.html
Add documentation for list endpoints: `datasets`, `versions` and `tables`
> docs: add documentation for list endpoints

- static/docs.css
instead of what there is before this PR
> feat: shorter header in more cases

- Jenkinsfile
It's not really a useful step, and is more consistent with other projects Data Infrastructure manages
> build: skip dev when merging

- app_worker.py
The main point of this PR is to have the structure of the main conversion loop be more like
1. ~code common to JSON and SQLite datasets
2. convert_json_to_csvs
3. ~code common to JSON and SQLite datasets
to be able to more easily add in different conversions in step 2
The second point of this PR is reducing the nesting level of functions/how many functions there are. To me, this makes the main loop a touch clearer.
----
Reviews can be commit-by-commit: each should be a step forward in the overall refactor
> refactor: to support sqlite to csv generation

- app.py
- app_aws.py
- app_worker.py
The change in 0455904fa3b211bd241f797d44ce77368a81da85 didn't quite achieve this: the delimiter parameter has to not be sent
> refactor: allow not sending delimiter when listing S3 keys

- app.py
- app_aws.py
- app_worker.py
Going a bit back and forth on this one, but now think clearer to just have separate functions for querying for keys and querying for folders, since they access different XML, and could return different data (e.g. keys can have a last-modified, but folders don't).
> refactor: specialise function to just folders

- templates/docs/index.html
Probably still needs to be tidied up, but at least there is less duplication
> docs: remove concepts section

- app.py
- test_app.py
This was a bit of an oversight that we didn't have this from the get-go. Note, there is no sign in or any way to modify any data from the API, and absolutely everything served by the API (and in the bucket that powers it) is for the public.
> feat: allow CORS

- static/docs.css
- templates/docs/index.html
The columns were much too wide on mobile view. So instead of
we now have
> docs: avoid fixed table width columns for better mobile view

- app.py
- mock_google_analytics_app.py
- test_app.py
This is so we can make more informed decisions on how to change the API later: lots of behaviour is controlled by query strings
> feat: send query string to Google Analytics

- requirements.txt
- requirements_test.txt
If used on a bucket without versioning, will give a better error message
> build(deps): bump sqlite-s3-query

- requirements.txt
- requirements_test.txt
They were encoded as the string #NA, but this was a bit of a hack. Empty cells appear to be a well supported way of saying a cell is... empty.
> build(deps): bump stream-write-ods to encode None as empty cells

- app_worker.py
- test_app.py
This is so we can move to SQLite from datasets currently supplied as JSON in a backwards-compatible way
> feat: convert SQLite to JSON

- app_worker.py
- test_app.py
We can't really depend on SQLite telling us the types of columns of results - if these are from _reports, so some SQL, then SQLite doesn't preserve the type information in many cases.
So although this looks a bit hacky, it stands the best chance of consistently working as things are changed internally - a date should always come out of SQLite as a string in the format YYYY-MM-DD, and if something is in that format, it should be treated as a date.
> feat: convert what seem to be dates to dates for ODS

- app_worker.py
- test_app.py
The Public Data API has the concept of "reports" in SQLite-based datasets. These are SQL scripts that define some sort of filtered or aggregated "report" on the data in the SQLite file where each report's data is exposed as a single ODS file, and and single CSV file.
The SQL scripts can be made of multiple statements, for example to create temporary table(s). Then the final statement is a SELECT to query over the temporary table(s) and/or the real tables.
The code, before this change, dealt with multiple SELECT statements by only ever exposing the data in the final SELECT statement as the data in the report.
This is now changed. Now if there are multiple SELECT statements in a report (that result in rows), they are all output:
- For the CSV output, all the rows from all the SELECTs are …
> feat: multi-statement reports expose data from each statement

- app_worker.py
- test_app.py
We are changing the report sheet names to be labelled by section rather than the report name due to Excel's sheet name character limits
> feat: name ods report sheet by section

- app_aws.py
- app_worker.py
- requirements_test.txt
- test_app.py
This increases the version of pylint, as a speculative change to see if it addresses linting failures of a separate PR:
> AttributeError: 'Attribute' object has no attribute 'value'
The version of pyyaml is bumped because the existing version has trouble building locally on my computer, raising:
> AttributeError: cython_sources
The changes in the code are to get it to pass pylint checks with its newer version.
> build(deps): bump pylint and pyyaml in dev requirements

- app.py
- app_logging.py
- app_worker.py
- requirements.in
- requirements.txt
- test_app.py
To be ready for the move from GOV.UK PaaS to DBT Platform, we're changing the logging format from ECS to ASIM.
It's still JSON, but with different fields. Heavily inspired by  https://github.com/uktrade/django-log-formatter-asim
> feat: move from ECS to ASIM logging

- app.py
- test_app.py
We are switching to using /pingdom/ping.xml instead of /healthcheck, have reconfigured in pingdom to reflect this so this rule can be removed.
> feat: delete previous pingdom endpoint

- app_worker.py
- test_app.py
This makes the worker write the current timestamp (seconds since epoch) to a file. This isn't used right now, but will be used when we move to DBT Platform.
There might be a follow up change - a command line to run to check if this file exists and has a recent timestamp.
> feat: add monitoring thread to worker that writes to heartbeat file

- README.md
- app_heartbeat.py
- app_worker.py
- test_app.py
This adds a basic CLI to check the heartbeat file.
This isn't used now, but will be used when we move to DBT Platform, that uses file-based heartbeats for backend workers.
> feat: basic CLI to check heartbeat

- requirements.txt
- requirements_test.txt
In preparation for moving to DBT Platform, we're making sure all dependencies are up to date.
sqlite-s3-query is not bumped since it seemed to result in errors in some tests.
> build(deps): bump most Python packages

- app_worker.py
- requirements.txt
- requirements_test.txt
sqlite-s3-query 0.0.68 creates a new connection for every call to the `query` function. As a result, transactions do not persist between one call to the `query` function and the next, therefore it's incorrect to pass it 'ROLLBACK', because there is now never a transaction in progress: calling ROLLBACK causes a SQLite Logic Error.
In addition, the isolation provided by the transactions prior to this change is now given by the separate connections, so there isn't a need for transactions at all. So, we can and do remove them.
Note that for each new `query` function that's generated by sqlite-s3-query, even over multiple calls to it, it will always query the same version of the sqlite file in the s3 bucket. And so even if the sqlite file is replaced between multiple calls to `query`, this …
> build(deps): bump sqlite-s3-query and remove explicit transactions

- test_app.py
The test_key_that_exists sometimes passed in CI, but sometimes now. Addressing this now in case there need to be code changes for the migration to DBT Platform, to make those changes less likely to be painful due to flaky tests.
> tests: make test less flaky by retrying

- .github/workflows/test.yml
Code Coverage doesn't seem to be showing at
https://app.codecov.io/gh/uktrade/public-data-api. Trying to explicitly use OIDC to see if that sorts it.
> ci: use OIDC for code coverage upload

- .github/workflows/test.yml
Since we have just moved from master to main as the default branch
> ci: run GitHub actions on main branch rather than master

- .github/workflows/test.yml
No matter what, with OIDC it seems to fail with the message:
> Upload failed: {"detail":"Failed token authentication, please double-check that
> your repository token matches in the Codecov UI, or review the docs
> ci: use token rather than OIDC for Codecov upload

- README.md
- app.py
This changes adds the GA4 server side. 
I am keeping the old implementation for two reasons:
1. We can run them side by side to make sure the data is the same across both UA and GA4.
2. To make sure that the new implementation works. I can't test this from my localhost.
> Feat/dt 1927 Adding GA4 server side

- requirements.txt
- requirements_test.txt
This is to address https://github.com/advisories/GHSA-g92j-qhmh-64v2
> build(deps): upgrade sentry-sdk

- requirements.txt
- requirements_test.txt
Update to the new version stream-write-ods that has optional use of Zip64.
> build(deps): update to stream-write-ods v0.0.25

- .pre-commit-config.yaml
- app_worker.py
This implements the update  in stream-write-ods to use Zip65 for [Large ODS files](https://github.com/uktrade/stream-write-ods#large-ods-files).
> feat: use stream_write_ods with Zip64 when data too big to support more data in ODS

- app.py
- app_worker.py
- test_app.py
This is because it was taking too long to do in the request response cycle, but also it was returning versions that appeared ready even though the backend worker had not completed processing them.
> feat: generate data.json metadata file from backend worker

- app_worker.py
This makes sure to pass bytes to signed_s3_request as the body (not a string or iterable of bytes or string).
> fix: saving data.json hash key

- app_worker.py
This is so older broken metadata files don't break saving of the file.
> fix: skip broken metadata files when generating data.json

- README.md
- mock_sentry_app.py
- start-services.sh
- test_app.py
Added secondary port (9001) to the container that runs the Minio server, such that the Minio console can be viewed in a browser (for local development purposes)
Tested locally by executing start-services.sh and I could see the console on http://localhost:9001
Sorry that the changes were made in one new big block of 'docker run' command rather than just changing the bits that need changing. Hopefully it's clear enough the two bits that I changed i.e. adding '-p 9001:9001' and '--console-address :9001' to the 'docker run' options' list
> Add port 9001 to container for Minio server

- README.md
- app.py
- app_worker.py
- requirements.in
- requirements.txt
- requirements_test.txt
- templates/docs.html
- test_app.py
This adds Apache Parquet to the output format list. This is done for 2 reasons:
- Apache Parquet is more and more the format used to transfer big datasets. Although our datasets are so far not really "big", the format is nevertheless fairly expected these days and users are often setup to ingest it
- To slowly increase our organisational knowledge of Parquet
The tweaks to testing that fires up processes, especially the addition of the sleep, is to make sure to catch stdout output, which for some reason takes longer with this change.
> feat: convert tables and reports to Parquet

- app_worker.py
This change wraps the code that converts to Parquet format with a try block to march forward in the case of ArrowNotImplementedError. This is to work around the error:
> ArrowNotImplementedError ("NumPyConverter doesn't implement <null> conversion."
> , 'Conversion failed for column <column_name> with type float64')
(The "<column_name>" in the real error has the name of the column).
That I suspect is due to Pandas schema detection assuming a column only has null in because it only null appears at the beginning, but then non-null values appear later.
This is causing a fair bit of noise in logs. Since we only introduced Parquet recently, for now I think this is the best option because it's not taking Parquet away from any files that already have it.
> fix: march forward with conversion if cannot convert to Parquet

- app_worker.py
There are more Parquet-related exceptions that prevent the file format conversion from progressing.
Instead of continuing to add to the list of exception types, have found the PyArrow exception base class at
https://github.com/apache/arrow/blob/fb8e8122f623f4548b22ece7485c4570d7ece1a6/python/pyarrow/error.pxi#L33C7-L33C21
(This is vey similary to previous fixes)
> fix: carry on in the face of more arrow-exceptions

- mock_google_analytics_app.py
This removes an unnecessary nonlocal variable in the mock GA server. While it doesn't change behaviour, it addresses a linting error.
> refactor: remove unnecessary nonlocal to fix linting
